### ISSUE TITLE
A Proposal for Functionality Classes for Random Number Generators V2.36

### ISSUE THREAD

**Issue by ricardo2000y** [g-g-sakura/AnotherAIS31TestTool#1]
Just a suggestion to update the link the latest version available of the draft.

[A Proposal for Functionality Classes for Random Number Generators V2.36](https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Certification/Interpretations/AIS_31_Functionality_classes_for_random_number_generators_e_2023.pdf?__blob=publicationFile&v=2)

Good luck with rest of the project.

**Comment by g-g-sakura** [comment]
Thank you for the information.
I will add the link to V2.36 with supplementary texts, as the test specification is dropped from V2.36.

Thank you again.

**Comment by g-g-sakura** [comment]
I added the link to V2.36, and the issue is closed.
